[package]
name = "transaction-manager-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
clap = {version = "4.5.18", features = ["derive"]}
transaction-manager-lib = { workspace = true }
