[package]
name = "transaction-manager-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
env_logger = { version = "0.11.5" }
